services:
  - type: web
    name: english-tutor-web
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn english_tutor_web.wsgi:application"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: english-tutor-db
          property: connectionString
      - key: RENDER
        value: true

databases:
  - name: english-tutor-db
    plan: free
