# Generated by Django 5.2.6 on 2025-09-29 21:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(help_text='Original user input')),
                ('input_method', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice')], default='text', max_length=10)),
                ('corrected_sentence', models.TextField(help_text='Grammar-corrected version')),
                ('has_errors', models.BooleanField(default=False, help_text='Whether grammar errors were found')),
                ('explanation', models.TextField(blank=True, help_text='Grammar correction explanation')),
                ('ai_response', models.TextField(help_text="AI's conversational response")),
                ('session_id', models.CharField(help_text='Session identifier', max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
